export const FETCH_ALL_VECHICLES_SUCCESS = 'FETCH_ALL_VECHICLES_SUCCESS';
export const FETCH_ALL_VECHICLES_ERROR = 'FETCH_ALL_VECHICLES_ERROR';
export const ADD_VECHICLE_SUCCESS = 'ADD_VECHICLES_SUCCESS';
export const ADD_VECHICLE_ERROR = 'ADD_VECHICLES_ERROR';
export const UPDATE_VECHICLE_SUCCESS = 'UPDATE_VECHICLES_SUCCESS';
export const UPDATE_VECHICLE_ERROR = 'UPDATE_VECHICLES_ERROR';


export const FETCH_ALL_VENDORS_SUCCESS = 'FETCH_ALL_VENDORS_SUCCESS';
export const FETCH_ALL_VENDORS_ERROR = 'FETCH_ALL_VENDORS_ERROR';
export const ADD_VENDOR_SUCCESS = 'ADD_VENDOR_SUCCESS';
export const ADD_VENDOR_ERROR = 'ADD_VENDOR_ERROR';
export const UPDATE_VENDOR_SUCCESS = 'UPDATE_VENDOR_SUCCESS';
export const UPDATE_VENDOR_ERROR = 'UPDATE_VENDOR_ERROR';

export const FETCH_ALL_OFFICE_SUCCESS = 'FETCH_ALL_OFFICE_SUCCESS';
export const FETCH_ALL_OFFICE_ERROR = 'FETCH_ALL_OFFICE_ERROR';
export const ADD_OFFICE_SUCCESS = 'ADD_OFFICE_SUCCESS';
export const ADD_OFFICE_ERROR = 'ADD_OFFICE_ERROR';
export const UPDATE_OFFICE_SUCCESS = 'UPDATE_OFFICE_SUCCESS';
export const UPDATE_OFFICE_ERROR = 'UPDATE_OFFICE_ERROR';

export const FETCH_ALL_TRIP_SUCCESS = 'FETCH_ALL_TRIP_SUCCESS';
export const FETCH_ALL_TRIP_ERROR = 'FETCH_ALL_TRIP_ERROR';
export const ADD_TRIP_SUCCESS = 'ADD_TRIP_SUCCESS';
export const ADD_TRIP_ERROR = 'ADD_TRIP_ERROR';
export const UPDATE_TRIP_SUCCESS = 'UPDATE_TRIP_SUCCESS';
export const UPDATE_TRIP_ERROR = 'UPDATE_TRIP_ERROR';


export const FETCH_ALL_DRIVER_SUCCESS = 'FETCH_ALL_DRIVER_SUCCESS';
export const FETCH_ALL_DRIVER_ERROR = 'FETCH_ALL_DRIVER_ERROR';
export const ADD_DRIVER_SUCCESS = 'ADD_DRIVER_SUCCESS';
export const ADD_DRIVER_ERROR = 'ADD_DRIVER_ERROR';
export const UPDATE_DRIVER_SUCCESS = 'UPDATE_DRIVER_SUCCESS';
export const UPDATE_DRIVER_ERROR = 'UPDATE_DRIVER_ERROR';


export const OPEN_MODAL = 'OPEN';
export const UPDATED_CLOSE_MODAL = 'UPDATED_CLOSE';
